#!/bin/bash

if [[ `uname` == 'Linux' ]]; then
  echo "Linux detected"
  if [[ ! `type aptitude` ]]; then
    echo "installing aptitude"
    sudo apt-get install aptitude
  fi
  if [[ ! `type brew` ]]; then
    if [[ -d /home/linuxbrew/.linuxbrew/bin ]]; then
      echo "brew not in path - correcting"
      export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
    else
      sudo apt-get install build-essential curl file git
      sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
      export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
    fi
  fi
  if [[ ! `type fish` ]]; then
    echo "fish not found - installing"
    brew install fish
  else
    echo "fish found"
  fi
elif [[ `uname` == 'Darwin' ]]; then
  echo "Darwin detected"
  if [[ ! `type brew` ]]; then
    echo "brew not found - installing"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  else
    echo "brew found"
  fi
  if [[ ! `type fish` ]]; then
    echo "fish not found - installing"
    brew install fish
  else
    echo "fish found"
  fi
fi

# clone the initial repo
if [[ ! -d $HOME/.config/fish/.git ]]; then
  rm -rf $HOME/.config/fish
  git clone git@github.com:jhessin/fish.git $HOME/.config/fish
fi

fish $HOME/.config/fish/setup.fish
